### ISSUE TITLE
Support for relative dates

### ISSUE THREAD

**Issue by Luehrsen** [Rarst/wp-date#5]
Especially for fast moving content blogs having relative dates like 'five minutes ago' is a real treat. Maybe add support to generate these strings into the object. 

https://stackoverflow.com/questions/2690504/php-producing-relative-date-time-from-timestamps

**Comment by Rarst** [comment]
WP already has `human_time_diff()` for it?

There is a trac ticket about improving that (which I hadn't got to yet) https://core.trac.wordpress.org/ticket/29849

**Comment by Luehrsen** [comment]
Goddammit, i did not know that function...
